#!/usr/bin/env python3
"""
Synesthesia Population Generator
Intelligently generates diverse agent populations based on society description

User describes the society they want, LLM generates appropriate demographics,
then we create individual agent profiles with realistic mental health baselines.
"""

import json
import random
from typing import Dict, Any, List
from dataclasses import dataclass, field, asdict
from openai import OpenAI
import os
from dotenv import load_dotenv

load_dotenv()


@dataclass
class SocietyConfig:
    """High-level society configuration generated by LLM"""
    society_description: str
    total_population: int
    
    # Demographics (percentages that sum to 100)
    demographics: Dict[str, float] = field(default_factory=dict)
    # Example: {"students": 60, "faculty": 20, "service_workers": 15, "retirees": 5}
    
    # Age distributions per demographic
    age_ranges: Dict[str, tuple] = field(default_factory=dict)
    # Example: {"students": (18, 25), "faculty": (30, 65)}
    
    # Common stressors in this society
    stressors: List[str] = field(default_factory=list)
    # Example: ["academic_pressure", "financial_stress", "social_isolation"]
    
    # Mental health baseline ranges per demographic
    mental_health_baselines: Dict[str, Dict[str, tuple]] = field(default_factory=dict)
    # Example: {"students": {"anxiety": (0.4, 0.7), "depression": (0.2, 0.5)}}
    
    # Social structure
    family_structure: str = "mixed"  # nuclear, extended, single, mixed
    community_cohesion: float = 0.5  # 0.0 (isolated) to 1.0 (tight-knit)
    
    # Economic factors
    economic_stress_level: float = 0.5  # 0.0 (wealthy) to 1.0 (struggling)
    unemployment_rate: float = 0.05
    
    # Cultural factors
    mental_health_stigma: float = 0.5  # 0.0 (no stigma) to 1.0 (high stigma)
    help_seeking_culture: float = 0.5  # 0.0 (never seek help) to 1.0 (proactive)


@dataclass
class AgentProfile:
    """Individual agent profile"""
    agent_id: int
    name: str
    age: int
    role: str  # student, lawyer, parent, etc.
    sub_role: str  # freshman, public defender, single parent, etc.
    
    # Demographics
    gender: str
    family_status: str  # single, married, divorced, widowed
    has_children: bool
    num_children: int = 0
    
    # Personality
    personality_traits: List[str] = field(default_factory=list)
    # Example: ["introverted", "perfectionist", "optimistic"]
    
    # Mental health state
    mental_health: Dict[str, float] = field(default_factory=dict)
    # Example: {"anxiety": 0.6, "depression": 0.3, "stress": 0.7, "wellbeing": 0.4}
    
    # Daily schedule (hours when active)
    work_hours: List[int] = field(default_factory=list)
    sleep_hours: List[int] = field(default_factory=list)
    active_hours: List[int] = field(default_factory=list)
    
    # Social connections (agent IDs)
    family_connections: List[int] = field(default_factory=list)
    friend_connections: List[int] = field(default_factory=list)
    work_connections: List[int] = field(default_factory=list)
    
    # Stressors
    stressors: List[str] = field(default_factory=list)
    
    # Coping mechanisms
    coping_mechanisms: List[str] = field(default_factory=list)
    # Example: ["exercise", "social_support", "therapy", "substance_use"]
    
    # Help-seeking behavior
    therapy_access: bool = False
    therapy_willingness: float = 0.5  # 0.0 (never) to 1.0 (proactive)
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class SocietyGenerator:
    """Generates society configuration from natural language description"""
    
    def __init__(self, api_key: str = None, base_url: str = None, model: str = None):
        self.client = OpenAI(
            api_key=api_key or os.getenv("LLM_API_KEY"),
            base_url=base_url or os.getenv("LLM_BASE_URL")
        )
        self.model = model or os.getenv("LLM_MODEL_NAME", "qwen/qwen2-7b-instruct")
    
    def generate_society_config(
        self,
        description: str,
        population: int
    ) -> SocietyConfig:
        """
        Use LLM to generate society configuration from description
        
        Args:
            description: Natural language description of the society
            population: Total population size
            
        Returns:
            SocietyConfig with demographics, stressors, baselines, etc.
        """
        
        prompt = f"""You are a sociologist and mental health expert. Generate a realistic society configuration based on this description:

**Society Description:** {description}
**Total Population:** {population:,} people

Generate a detailed society configuration as JSON with the following structure:

{{
  "demographics": {{
    "role_name": percentage,
    ...
  }},
  "age_ranges": {{
    "role_name": [min_age, max_age],
    ...
  }},
  "stressors": ["stressor1", "stressor2", ...],
  "mental_health_baselines": {{
    "role_name": {{
      "anxiety": [min, max],
      "depression": [min, max],
      "stress": [min, max],
      "wellbeing": [min, max]
    }},
    ...
  }},
  "family_structure": "nuclear|extended|single|mixed",
  "community_cohesion": 0.0-1.0,
  "economic_stress_level": 0.0-1.0,
  "unemployment_rate": 0.0-1.0,
  "mental_health_stigma": 0.0-1.0,
  "help_seeking_culture": 0.0-1.0
}}

**Guidelines:**
- Demographics should sum to 100%
- Include diverse roles: students, workers, parents, retirees, unemployed, etc.
- Mental health baselines should reflect realistic patterns for each demographic
- Stressors should be specific to this society type
- All values between 0.0 and 1.0 represent scales (0=none, 1=maximum)

**Example roles:** students, teachers, healthcare_workers, tech_workers, retail_workers, 
lawyers, parents, single_parents, retirees, unemployed, mental_health_professionals

Return ONLY valid JSON, no markdown or explanation."""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a sociologist expert. Return only valid JSON."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7,
                response_format={"type": "json_object"}
            )
            
            result = json.loads(response.choices[0].message.content)
            
            # Normalize demographics (handle both 0.6 and 60 formats)
            demographics = result.get("demographics", {})
            normalized_demographics = {}
            for role, pct in demographics.items():
                # If value is < 1, assume it's a decimal (0.6 = 60%)
                if pct < 1:
                    normalized_demographics[role] = pct * 100
                else:
                    normalized_demographics[role] = pct
            
            # Parse into SocietyConfig
            return SocietyConfig(
                society_description=description,
                total_population=population,
                demographics=normalized_demographics,
                age_ranges={k: tuple(v) for k, v in result.get("age_ranges", {}).items()},
                stressors=result.get("stressors", []),
                mental_health_baselines=result.get("mental_health_baselines", {}),
                family_structure=result.get("family_structure", "mixed"),
                community_cohesion=result.get("community_cohesion", 0.5),
                economic_stress_level=result.get("economic_stress_level", 0.5),
                unemployment_rate=result.get("unemployment_rate", 0.05),
                mental_health_stigma=result.get("mental_health_stigma", 0.5),
                help_seeking_culture=result.get("help_seeking_culture", 0.5)
            )
            
        except Exception as e:
            print(f"Error generating society config: {e}")
            # Return default config
            return self._get_default_config(description, population)
    
    def _get_default_config(self, description: str, population: int) -> SocietyConfig:
        """Fallback default configuration"""
        return SocietyConfig(
            society_description=description,
            total_population=population,
            demographics={
                "students": 25,
                "working_adults": 50,
                "parents": 20,
                "retirees": 5
            },
            age_ranges={
                "students": (10, 22),
                "working_adults": (23, 65),
                "parents": (25, 55),
                "retirees": (65, 90)
            },
            stressors=["work_stress", "financial_pressure", "social_isolation"],
            mental_health_baselines={
                "students": {
                    "anxiety": (0.3, 0.6),
                    "depression": (0.2, 0.4),
                    "stress": (0.4, 0.7),
                    "wellbeing": (0.4, 0.7)
                }
            }
        )


class PopulationGenerator:
    """Generates individual agent profiles from society configuration"""
    
    FIRST_NAMES = [
        "Emma", "Liam", "Olivia", "Noah", "Ava", "Ethan", "Sophia", "Mason",
        "Isabella", "William", "Mia", "James", "Charlotte", "Benjamin", "Amelia",
        "Lucas", "Harper", "Henry", "Evelyn", "Alexander", "Abigail", "Michael",
        "Emily", "Daniel", "Elizabeth", "Matthew", "Sofia", "Jackson", "Avery",
        "David", "Ella", "Joseph", "Scarlett", "Samuel", "Grace", "Sebastian"
    ]
    
    LAST_NAMES = [
        "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller",
        "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez",
        "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
        "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark",
        "Ramirez", "Lewis", "Robinson", "Walker", "Young", "Allen", "King"
    ]
    
    def generate_population(self, config: SocietyConfig) -> List[AgentProfile]:
        """
        Generate individual agent profiles based on society configuration
        
        Args:
            config: SocietyConfig from LLM
            
        Returns:
            List of AgentProfile objects
        """
        agents = []
        agent_id = 0
        
        # Generate agents for each demographic
        for role, percentage in config.demographics.items():
            count = int(config.total_population * (percentage / 100))
            
            for _ in range(count):
                agent = self._create_agent(
                    agent_id=agent_id,
                    role=role,
                    config=config
                )
                agents.append(agent)
                agent_id += 1
        
        # Create social connections
        agents = self._create_social_network(agents, config)
        
        return agents
    
    def _create_agent(
        self,
        agent_id: int,
        role: str,
        config: SocietyConfig
    ) -> AgentProfile:
        """Create a single agent profile"""
        
        # Generate name
        name = f"{random.choice(self.FIRST_NAMES)} {random.choice(self.LAST_NAMES)}"
        
        # Generate age
        age_range = config.age_ranges.get(role, (18, 65))
        age = random.randint(age_range[0], age_range[1])
        
        # Generate mental health baseline
        mh_baseline = config.mental_health_baselines.get(role, {})
        mental_health = {}
        for metric, (min_val, max_val) in mh_baseline.items():
            mental_health[metric] = random.uniform(min_val, max_val)
        
        # Default mental health if not specified
        if not mental_health:
            mental_health = {
                "anxiety": random.uniform(0.2, 0.5),
                "depression": random.uniform(0.1, 0.4),
                "stress": random.uniform(0.3, 0.6),
                "wellbeing": random.uniform(0.5, 0.8)
            }
        
        # Generate schedule based on role
        work_hours, sleep_hours, active_hours = self._generate_schedule(role, age)
        
        # Generate personality
        personality_traits = self._generate_personality()
        
        # Therapy access based on help-seeking culture
        therapy_access = random.random() < config.help_seeking_culture
        therapy_willingness = random.uniform(
            max(0, config.help_seeking_culture - 0.3),
            min(1, config.help_seeking_culture + 0.3)
        )
        
        return AgentProfile(
            agent_id=agent_id,
            name=name,
            age=age,
            role=role,
            sub_role=self._generate_sub_role(role, age),
            gender=random.choice(["male", "female", "non-binary"]),
            family_status=self._generate_family_status(age),
            has_children=age > 25 and random.random() < 0.4,
            num_children=random.randint(1, 3) if age > 25 and random.random() < 0.4 else 0,
            personality_traits=personality_traits,
            mental_health=mental_health,
            work_hours=work_hours,
            sleep_hours=sleep_hours,
            active_hours=active_hours,
            stressors=random.sample(config.stressors, min(3, len(config.stressors))),
            coping_mechanisms=self._generate_coping_mechanisms(),
            therapy_access=therapy_access,
            therapy_willingness=therapy_willingness
        )
    
    def _generate_schedule(self, role: str, age: int) -> tuple:
        """Generate work, sleep, and active hours"""
        # Work hours
        if "student" in role.lower():
            work_hours = list(range(8, 16))  # 8am-4pm classes
        elif "retiree" in role.lower():
            work_hours = []
        else:
            work_hours = list(range(9, 18))  # 9am-6pm
        
        # Sleep hours
        if age < 25:
            sleep_hours = list(range(0, 7))  # midnight-7am (young people sleep late)
        else:
            sleep_hours = list(range(23, 24)) + list(range(0, 6))  # 11pm-6am
        
        # Active hours (not working or sleeping)
        all_hours = set(range(24))
        active_hours = list(all_hours - set(work_hours) - set(sleep_hours))
        
        return work_hours, sleep_hours, active_hours
    
    def _generate_sub_role(self, role: str, age: int) -> str:
        """Generate specific sub-role"""
        sub_roles = {
            "students": ["freshman", "sophomore", "junior", "senior", "graduate_student"],
            "teachers": ["elementary_teacher", "high_school_teacher", "professor"],
            "healthcare_workers": ["nurse", "doctor", "therapist", "medical_assistant"],
            "tech_workers": ["software_engineer", "data_scientist", "product_manager"],
            "parents": ["single_parent", "working_parent", "stay_at_home_parent"]
        }
        return random.choice(sub_roles.get(role, [role]))
    
    def _generate_family_status(self, age: int) -> str:
        """Generate family status based on age"""
        if age < 25:
            return random.choice(["single", "single", "single", "in_relationship"])
        elif age < 40:
            return random.choice(["single", "married", "in_relationship", "divorced"])
        else:
            return random.choice(["married", "married", "divorced", "widowed"])
    
    def _generate_personality(self) -> List[str]:
        """Generate personality traits"""
        traits = [
            "introverted", "extroverted", "optimistic", "pessimistic",
            "perfectionist", "laid_back", "anxious", "confident",
            "empathetic", "analytical", "creative", "practical"
        ]
        return random.sample(traits, 3)
    
    def _generate_coping_mechanisms(self) -> List[str]:
        """Generate coping mechanisms"""
        mechanisms = [
            "exercise", "social_support", "therapy", "meditation",
            "substance_use", "avoidance", "problem_solving", "creative_expression"
        ]
        return random.sample(mechanisms, random.randint(2, 4))
    
    def _create_social_network(
        self,
        agents: List[AgentProfile],
        config: SocietyConfig
    ) -> List[AgentProfile]:
        """Create social connections between agents"""
        # TODO: Implement social network generation
        # - Family connections (parents-children, siblings)
        # - Friend connections (based on age, role, proximity)
        # - Work connections (colleagues)
        return agents


def main():
    """Example usage"""
    print("="*60)
    print("🌍 SYNESTHESIA POPULATION GENERATOR")
    print("="*60)
    print()
    
    # Example: Generate a college town
    description = "Small college town with 10,000 people, high academic pressure, diverse student body, some economic stress"
    population = 10000
    
    print(f"📝 Society Description: {description}")
    print(f"👥 Population: {population:,}")
    print()
    
    # Step 1: Generate society configuration
    print("🤖 Generating society configuration with LLM...")
    generator = SocietyGenerator()
    config = generator.generate_society_config(description, population)
    
    print("✅ Society configuration generated!")
    print(f"\n📊 Demographics:")
    for role, pct in config.demographics.items():
        count = int(population * (pct / 100))
        print(f"   {role}: {pct}% ({count:,} people)")
    
    print(f"\n⚠️  Stressors: {', '.join(config.stressors)}")
    print(f"🤝 Community Cohesion: {config.community_cohesion:.2f}")
    print(f"💰 Economic Stress: {config.economic_stress_level:.2f}")
    print(f"🏥 Help-Seeking Culture: {config.help_seeking_culture:.2f}")
    print()
    
    # Step 2: Generate individual agents
    print("👤 Generating individual agent profiles...")
    pop_gen = PopulationGenerator()
    agents = pop_gen.generate_population(config)
    
    print(f"✅ Generated {len(agents):,} agent profiles!")
    print()
    
    # Show sample agents
    print("📋 Sample Agents:")
    for agent in agents[:5]:
        print(f"\n   {agent.name} (ID: {agent.agent_id})")
        print(f"   Role: {agent.role} - {agent.sub_role}")
        print(f"   Age: {agent.age}, {agent.gender}, {agent.family_status}")
        print(f"   Mental Health: Anxiety={agent.mental_health.get('anxiety', 0):.2f}, "
              f"Depression={agent.mental_health.get('depression', 0):.2f}")
        print(f"   Stressors: {', '.join(agent.stressors)}")
    
    # Save to file
    output_file = "population_config.json"
    with open(output_file, 'w') as f:
        json.dump({
            "society_config": asdict(config),
            "agents": [agent.to_dict() for agent in agents]
        }, f, indent=2)
    
    print(f"\n💾 Saved to {output_file}")
    print("\n" + "="*60)


if __name__ == "__main__":
    main()
